name: Repo Events
on: [push, pull_request, issues]

jobs: 
  checkout-test:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo $GITGUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3