name: first workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: check version
        run: |
          node -v
          npm -v