name: Status Check functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
          - name: 1
            run: sleep 20
          - name: runs on failure
            if: failure()
            run: echo 'Runs only on failure'
          - name: run on success
            if: success()
            run: echo 'runs on success'
          - name: runs always
            if: always()
            run: echo 'Always runs'
          - name: Runs when Canclled
            if: cancelled()
            run: echo 'Runs on canclled'
            
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
          - run: echo "Job 2"
