name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "TEXT"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: santoshPagire/reusable_workflow/.github/workflows/reusable.yml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}