name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "TEXT"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: santoshPagire/reusable_workflow/.github/workflows/reusable.yml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  calling-a-reusable-wf-in-the-same-repo:
        uses: santoshPagire/Github_Actions-Workflows/.github/workflows/reusable-workflow.yml@main
  using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wf-in-the-same-repo
        steps:
          - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}